### ISSUE TITLE
How to write unit tests with accept payment nonce

### ISSUE THREAD

**Issue by blakebyrnes** [AuthorizeNet/sdk-node#15]
Is there a way in the sdk to create payment nonces so we can write unit tests?

**Comment by adavidw** [comment]
Not exactly an officially supported way, but...

If you step through the Accept.js script and it's companion, acceptcore.js, you'll eventually notice that acceptcore.js calls a SecurePaymentContainerRequest API method to get the nonce back. You can hit that method yourself in the same way. Again, completely unsupported and could stop working any time.

See details here:
https://community.developer.authorize.net/t5/Integration-and-Testing/Accept-JS-and-Integration-Testing/m-p/57232/highlight/true#M31961

Hopefully, we'll have an officially supported way to retrieve a nonce directly at some point.
