### ISSUE TITLE
No email address under billTo information

### ISSUE THREAD

**Issue by jxcheng008** [AuthorizeNet/sdk-node#16]
I have set an email information under the billTo but it does not display on the email notification sent to the owner.

**Comment by ashtru** [comment]
Email is not supported by APIs as part of billing information, even though the SDKs have email in `billTo` field. Email is instead sent as part of customer profile information for the customer.

A solution would be to create a customer profile with the email field.
Then create a customer payment profile(it has payment and billTo information) of above customer profile with the billTo information.
Follow the [sample codes](https://github.com/AuthorizeNet/sample-code-node/blob/master/CustomerProfiles/create-customer-profile.js#L24) for example.
