### ISSUE TITLE
How to adjust the amount in Pre-Authorized transaction?

### ISSUE THREAD

**Issue by kunalwatkar** [AuthorizeNet/sdk-node#17]
Hi,

I am new at using Payment APIs. Currently, I have a Retail website, where I am using AuthorizeNet SDK to process payments.

I am using "authOnlyTransaction" transaction, to authorize the credit card for the amount of ordered items.
When I ship the items, I use "priorAuthCaptureTransaction" transaction to charge the card. Also, I add Invoice number to the transaction at this step, as I only create a order after validating a credit card in "authOnlyTransaction" step. Is this correct way to process transaction?

Also, some times, my customers changes the order items after order is placed. In that how can I adjust the amount? 
1. Should I void the entire transaction, and create a new "authOnlyTransaction" ? OR
2. Is there any way to adjust the amount for already authorized card?

**Comment by adavidw** [comment]
Hi @kunalwatkar,

What you are doing with the priorAuthCaptureTransaction is the best way to do what you want. If you need to adjust the amount, you can always adjust the amount downward by sending a different amount in the priorAuthCaptureTransaction request. If you need to adjust the amount upwards, the only way to do that would be to void the transaction and then do a new authorization for a new total, or capture the existing authroization and only do a new authorization for the additional amount added.
