### ISSUE TITLE
package should be published pre-compiled (retaining ES6 Modules)

### ISSUE THREAD

**Issue by fxalvarezd** [AuthorizeNet/sdk-node#25]
Hello,
We're running into an issue when trying to minify running `create-react-app`.
Could you please publish the package pre-compiled (retaining ES6 Modules)

https://github.com/JedWatson/react-select/issues/1974

Thanks!

**Comment by TheDolo** [comment]
@fxalvarezd this is a backend node framework like Express or Hapi, not really for frontend react apps which would impose big security risks.

**Comment by vijayabraj** [comment]
@fxalvarezd Can you please elaborate the problem you are facing? Are you asking for a transpiled and minified version of the code?

**Comment by chsriniv9** [comment]
As per inputs provided by @vijayabraj this issue is being closed. Please feel free to re-open if you think otherwise.
