### ISSUE TITLE
Syntax Error in Node SDK

### ISSUE THREAD

**Issue by rahultiwari91** [AuthorizeNet/sdk-node#28]
Node application showing error when using the Authorizenet node SDK.
var ApiContracts = require('authorizenet').APIContracts;
var ApiControllers = require('authorizenet').APIControllers;

"SyntaxError: missing ) after argument list"

**Comment by sunnyrajrathod** [comment]
@rahultiwari91,
Can you help us with few more details about the issue?
Which node version are you using?

**Comment by rahultiwari91** [comment]
Node Version: 9.3.0
Authorize Net Node SDK: 1.0.4

If I am not requiring **authorizenet** then application working fine without any error.

**Comment by gnongsie** [comment]
Hi @rahultiwari91 ,

We are not able to reproduce this issue in the version that you specified.

If possible, kindly upgrade the Authorize.Net Node SDK to the latest version v1.0.6, which may help to resolve your issue.

**Comment by rahultiwari91** [comment]
Thanks. 

> Hi @rahultiwari91 ,
> 
> We are not able to reproduce this issue in the version that you specified.
> 
> If possible, kindly upgrade the Authorize.Net Node SDK to the latest version v1.0.6, which may help to resolve your issue.

thanks. Working now.
