### ISSUE TITLE
High Priority : How to make payment using stored credit card?

### ISSUE THREAD

**Issue by manish-wedigtech** [AuthorizeNet/sdk-node#32]
I want to make following process.
 1. check/authorize credit valid or not. if valid store into database.
 2. whenever I want, make payment using any secret token for multiple time.

How this is possible?

**Comment by mkarbowiak** [comment]
You could probably use those resources for both:
https://developer.authorize.net/api/reference/index.html#customer-profiles-create-customer-payment-profile
https://developer.authorize.net/api/reference/index.html#customer-profiles-validate-customer-payment-profile

**Comment by anuragg29** [comment]
Yes you can use our Customer profiles for storing the card details . 

More details at https://developer.authorize.net/api/reference/features/customer_profiles.html
