### ISSUE TITLE
npm ERR! cb() never called!

### ISSUE THREAD

**Issue by acharjee0712** [AuthorizeNet/sdk-node#40]

**Comment by gnongsie** [comment]
This is a closed bug related to Node.js 0.10.19
Please upgrade your node.

More details about the bug : 

- https://github.com/nodejs/node-v0.x-archive/issues/6263
- https://github.com/npm/npm/issues/2907

Happy Coding 👍

**Comment by chsriniv9** [comment]
Based on solution provided by @gnongsie closing this issue. Feel free to re-open in case further assistance required.
