### ISSUE TITLE
obj.forEach is not a function in APIContracts.TransactionRequestType class constructor

### ISSUE THREAD

**Issue by awwit** [AuthorizeNet/sdk-node#46]
This error occurs when passing arguments to the constructor of class `APIContracts.TransactionRequestType`.

```js
const lineItems = products.map(item =>
  new APIContracts.LineItemType({
    itemId: item.sku,
    name: item.name,
    description: item.slug,
    quantity: item.quantity,
    unitPrice: item.price
  })
)

const transactionRequest = new APIContracts.TransactionRequestType({
  transactionType: APIContracts.TransactionTypeEnum.AUTHCAPTURETRANSACTION,
  payment: paymentType,
  amount,
  lineItems, // <-- Accept only JS array, but in constructor transform to ArrayOfLineItem
  // https://github.com/AuthorizeNet/sdk-node/blob/master/lib/apicontracts.js#L3137
  order: orderDetails,
  tax,
  shipping
})

const request = new APIContracts.CreateTransactionRequest({ // <-- This throw error
  merchantAuthentication: auth,
  transactionRequest // <-- lineItems is ArrayOfLineItem, but in constructor an attempt
  // transform to ArrayOfLineItem again!
  // https://github.com/AuthorizeNet/sdk-node/blob/master/lib/apicontracts.js#L4771
})
```

Links to code (release 1.0.5):

APIContracts.TransactionRequestType:
https://github.com/AuthorizeNet/sdk-node/blob/ab098d70f1e4907a7251063008d339fecc0e0013/lib/apicontracts.js#L3137

APIContracts.CreateTransactionRequest:
https://github.com/AuthorizeNet/sdk-node/blob/ab098d70f1e4907a7251063008d339fecc0e0013/lib/apicontracts.js#L4771

**Comment by gnongsie** [comment]
Hi @awwit ,

Thank you for reaching out to us with this question.

The team has tried to reproduce this issue but the only way we can get the same error is if the parameter **`lineItems`** is an object and not an error.

Of course, we might be missing something. Could you give us an idea of what **`products`** might look like? Or if you'd like, you have the option of sending us the code used to create this request and we can extract **`products`** on our end.

-- Gabriel

**Comment by awwit** [comment]
Hi @gnongsie ,

Yes, if the `lineItems` is an `ArrayOfLineItem` (not js `Array`), then the code falls with an error that it cannot find the forEach function.

If `lineItems` is an `Array` containing `LineItemType` elements, then when converting an `Array` into a `ArrayOfLineItem`, it is repeated to convert an `object` in a `LineItemType` (which fails).

Later, I understand what you've planned. Therefore, I just replaced all your wrappers with native JS objects and everything worked as it should.

The code in your project is not very well written %)
In object constructors, many unnecessary operations are performed (setting values to null). Which I would like to avoid.

Examples of using your code confused me a little. As in them native objects are not used anywhere, but only just your own classes. Although you can go without them and the code will be much easier.

Thanks for answering me.

**Comment by gnongsie** [comment]
Hi,

The SDK was written in order to properly control the behavior of the code, making it as restrictive and explicit as we can in order to safeguard the data of the customers passing through the SDK.

I agree there can be improvements and I will discuss with the team regarding this.

Based on this, I will be closing this issue. Do let us know if you face further issues.
