### ISSUE TITLE
[Not error] Invalid property `length` of this._request

### ISSUE THREAD

**Issue by awwit** [AuthorizeNet/sdk-node#47]
https://github.com/AuthorizeNet/sdk-node/blob/ab098d70f1e4907a7251063008d339fecc0e0013/lib/apicontrollersbase.js#L83-L93

`this._request` is JS Object. It does not contain a length property.

These lines of code can be removed, since they do not affect anything:

https://github.com/AuthorizeNet/sdk-node/blob/ab098d70f1e4907a7251063008d339fecc0e0013/lib/apicontrollersbase.js#L86-L89

Proof in the `request` docs:
https://github.com/request/request#requestoptions-callback

**Comment by awwit** [comment]
Hi =)

I want to draw your attention to the fact that the headers you need are set automatically:
`Content-Length`: https://github.com/request/request/blob/master/request.js#L419-L440
`Content-Type`: https://github.com/request/request/blob/master/request.js#L1300-L1303

**Comment by gnongsie** [comment]
Hi,

A PR has been created for this issue and is pending review. Kindly be patient and we will try to release the fix as soon as possible.

**Comment by gnongsie** [comment]
Hi,

The fix for this has been released as part of the latest version v1.0.7. I will be closing this issue now.

Feel free to reach out to us if any further issues come up.
