### ISSUE TITLE
GetHostedPaymentPageRequest is missing customerProfileId

### ISSUE THREAD

**Issue by ar9jun** [AuthorizeNet/sdk-node#72]
Hello! I'm using the `GetHostedPaymentPageRequest` to use Accept Hosted in my project, and am trying to set up Customer Profiles to work with it. In the documentation for Accept Hosted, there should be a `customerProfileId` element in `GetHostedPaymentPageRequest`, however it's not available in this SDK. I took a look at the class definition and only saw `setTransactionRequest` and `setHostedPaymentSettings`.

**Comment by cennis-ck** [comment]
@ar9jun did you ever solve this? these docs are abysmal

**Comment by ar9jun** [comment]
@cennis-ck Yeah it was a bit tough with the docs, but it's been a little bit so I can't recall if this worked the way we wanted to or not back then, but we added it ourselves to the request like this:
```
var hostedPaymentPageRequest = new ApiContracts.GetHostedPaymentPageRequest();
hostedPaymentPageRequest["customerProfileId"] = "xxxxxxxxxxxxxx"
```
Check the `getRequest.getJSON()` to make sure it shows up still in the request, and it should get sent to GetHostedPaymentPageController.

I hope it works for you! Good luck 💪
