### ISSUE TITLE
Security vulnerability in dependency

### ISSUE THREAD

**Issue by jonmast** [AuthorizeNet/sdk-node#85]
The "qs" package has [a vulnerability](https://github.com/advisories/GHSA-hrpp-h998-j3pp). It is depended upon via the deprecated "request" package which presumably won't be updated. This will likely require removing the "request" dependency to fix.

**Comment by mattdknapp** [comment]
I see that the PR by @wilau2 was closed. Is there any plan to address this moving forward?

**Comment by smartersign** [comment]
This vulnerability still exists in July 2024, will the PR by @wilau2 be merged?

**Comment by smartersign** [comment]
I do see that the @wilau2 PR uses the `got` package which I believe will break CommonJS compatibility.. perhaps that is why it hasn't been implemented

**Comment by wilau2** [comment]
It works from my fork : 
    "authorizenet": "https://github.com/wilau2/sdk-node",

**Comment by gnongsie** [comment]
We have removed the offending `request` package with the more stable `axios` package, which should not have these security findings.
You can use the latest version : **`v1.0.9`**
Closing this issue.
