### ISSUE TITLE
Expected release date?

### ISSUE THREAD

**Issue by zenweasel** [AuthorizeNet/sdk-node#9]
Very excited to discover this here. We would love to migrate over from our current SDK to this "official" one. When you expect to have an "finished" version available?

We would be willing to be involved in testing it if this is nearing completion.

**Comment by brianmc** [comment]
Hi Brent, we're actually almost complete so would love you to try it out and give us any feedback.  You can also try the sample code here: https://github.com/AuthorizeNet/accept-sample-ios.git 

We're hoping to make this a production-ready, beta version in the coming days so any input you have would be much appreciated.

Thanks,

Brian
